### ISSUE TITLE
Getting 'error: no such package' when trying to add it

### ISSUE THREAD

**Issue by MichaelPolla** [oskarszoon/meteor-bootstrap-daterangepicker#6]
Hi,
I wanted to add your package, but when I do :
meteor add lofsteinn:bootstrap3-daterangepicker
I get : "error: no such package".

My meteor version is the latest (1.1.0.2).

Thanks for the help.
Best regards.

**Comment by jimmiebtlr** [comment]
Your missing a 't' as the 4th character.

**Comment by MichaelPolla** [comment]
Thanks for your reply.

The 't' is missing in the instructions given on the homepage :
![screenshot1435592076 png](https://cloud.githubusercontent.com/assets/10487171/8411615/424a6920-1e85-11e5-9845-342020fa91b9.png)

Now it's working :-)
